export enum FILE_EXTENSION {
  '.js' = 'javascript.svg',
  '.ts' = 'typescript.svg',
  '.html' = 'html.svg',
  '.css' = 'css.svg',
  '.jsx' = 'jsx.svg',
  '.tsx' = 'typescript.svg',
  '.py' = 'python.svg',
  '.babelrc' = 'babel.svg',
  '.vue' = 'vue.svg',
  '.gitignore' = 'git.svg',
  '.md' = 'markdown.svg',
  '.less' = 'less.svg',
  '.json' = 'json.svg',
  '.sass' = 'sass.svg',
  '.scss' = 'scss.svg',
  '.svg' = 'image.svg',
  '.zip' = 'archive.svg',
  '.rar' = 'archive.svg',
  '.7z' = 'archive.svg',
  '.tar' = 'archive.svg',
  '.gz' = 'archive.svg',
  '.bzip2' = 'archive.svg',
  '.xz' = 'archive.svg',
  '.bz2' = 'archive.svg',
  DEFAULT = 'default.svg',
}
export enum FILENAME {
  'package.json' = 'package.svg',
  'package-lock.json' = 'package.svg',
  'tsconfig.json' = 'tsconfig.svg',
  'babel.config.json' = 'babel.svg',
  'babel.json' = 'babel.svg',
  'LICENSE' = 'license.svg',
  '.eslintrc.json' = 'eslint.svg',
}
